### ISSUE TITLE
Please release 0.7.1

### ISSUE THREAD

**Issue by arobertn** [sirthias/scala-ssh#35]
The unreleased 0.7.1 depends on the new name of sshj (com.hierynomus instead of net.schmizz), the first release (0.11) of which fixes:

https://github.com/hierynomus/sshj/issues/54

The 0.7.0 depends on net.schmizz.sshj and there is no way to override this to use a later version with the fix since the name is different.

So, please either make 0.7.1 or a snapshot available on Maven.  Thanks!

**Comment by bphelan** [comment]
Yes, please.  With pull request #19 if possible!

**Comment by dimbleby** [comment]
I'm currently seeing problems which I believe are resolved by hierynomus/sshj#186 - available from release 0.12 of that project.

So a big thumbs-up to: please ship a fresh release with updated dependencies.  But if you could go (at least) one step further to 0.12, that would be great!

**Comment by sirthias** [comment]
I'm sorry, but I won't be able to maintain this library anymore and will also not publish any further releases.
I'll update the README to reflect this new state.

If anyone is interesting in maintaining his/her fork and publish subsequent releases I'd be happy to include a prominent forwarding pointer, so people can find the "continuation project".

**Comment by bphelan** [comment]
No problem - understandable.  Thanks for all your work on this to date!

My team have volunteered to maintain it; we've been publishing our own internal version anyway.  
Parked here: https://github.com/veact/scala-ssh.  Will tidy up and publish to maven central in the next week.

**Comment by sirthias** [comment]
Ok, great.
I've just updated the README with a pointer.
Thank you!

**Comment by arobertn** [comment]
@bphelan Thanks for offering to step up.  Any updated timeline for packaging/releasing 0.7.1 though?

**Comment by bphelan** [comment]
@arobertn, v0.8.0 is now live -- details here: https://github.com/veact/scala-ssh/blob/master/CHANGELOG
